// Code generated by MockGen. DO NOT EDIT.
// Source: timeline-service/internal/delivery/rest/timeline (interfaces: TimelineService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/timeline_service.go -package=mocks timeline-service/internal/delivery/rest/timeline TimelineService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	timeline "timeline-service/internal/domain/timeline"

	gomock "go.uber.org/mock/gomock"
)

// MockTimelineService is a mock of TimelineService interface.
type MockTimelineService struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineServiceMockRecorder
	isgomock struct{}
}

// MockTimelineServiceMockRecorder is the mock recorder for MockTimelineService.
type MockTimelineServiceMockRecorder struct {
	mock *MockTimelineService
}

// NewMockTimelineService creates a new mock instance.
func NewMockTimelineService(ctrl *gomock.Controller) *MockTimelineService {
	mock := &MockTimelineService{ctrl: ctrl}
	mock.recorder = &MockTimelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineService) EXPECT() *MockTimelineServiceMockRecorder {
	return m.recorder
}

// GetUserTimeline mocks base method.
func (m *MockTimelineService) GetUserTimeline(ctx context.Context, userID string) ([]timeline.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTimeline", ctx, userID)
	ret0, _ := ret[0].([]timeline.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTimeline indicates an expected call of GetUserTimeline.
func (mr *MockTimelineServiceMockRecorder) GetUserTimeline(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTimeline", reflect.TypeOf((*MockTimelineService)(nil).GetUserTimeline), ctx, userID)
}
